src/mako/cli/output/Output.php
src/mako/cli/output/formatter/Formatter.php
src/mako/cli/output/formatter/FormatterInterface.php
src/mako/cli/output/helpers/Table.php
src/mako/error/handlers/CLIHandler.php
tests/unit/cli/output/OutputTest.php
tests/unit/cli/output/formatter/FormatterTest.php
tests/unit/cli/output/helpers/TableTest.php

Changes:
* Added a ```Formatter::escape()``` method. 
* Fixed a bug that caused the command line exception handler to fail when trying to handle a unclosed formatting tag exception. 
* Renamed the ```stripFormatting``` method to ```strip```.
* Added a "clear" style to the formatter.
And I added tests :)

Added Formatter::escape() method and fixed a bug with the exception handler

---

src/mako/cli/output/helpers/Countdown.php
src/mako/reactor/Command.php
tests/README.md
tests/unit/cli/output/helpers/CountdownTest.php

I have added a CLI countdown output helper along with tests.
The tests take 7 seconds in total (since its a countdown :p) so I added the ```@slow``` group to it so that they can be skipped when running tests locally using ```--exclude-group slow```.

Added cli countdown helper

---

src/mako/database/midgard/ORM.php
tests/unit/database/midgard/ORMTest.php

PostgreSQL returns booleans as the strings "t" and "f". This modification allows those values to be properly casted by the automatic scalar casting.

Add support for Postgres booleans in scalar casting.

---

src/mako/application/services/CommandBusService.php
src/mako/commander/CommandBus.php
src/mako/commander/CommandBusInterface.php
src/mako/commander/CommandHandlerInterface.php
src/mako/commander/CommandInterface.php
src/mako/commander/SelfHandlingCommandInterface.php
src/mako/syringe/ContainerAwareTrait.php
tests/unit/commander/CommandBusTest.php

CQRS has become popular pattern where I work.
We have created a Command Bus for Mako and I thought that it would be nice if it was a part of the core.
I also included a CommandBusService for people who like to take advantage of the ContainerAwareTrait.

Command Bus

---

src/mako/validator/Validator.php

There are 2 small errors in those functions. I think this was caused during the version upgrade that changed the way attributes are parsed.
The original '$date' variable becomes a object so is not possible to parse it as the original string to compare the dates.

Fix 'Before' and 'After' rules

---

composer.json
src/mako/application/services/DatabaseService.php
src/mako/application/services/PaginationFactoryService.php
src/mako/database/midgard/Query.php
src/mako/database/query/Query.php
src/mako/database/query/QueryConvenienceTrait.php
src/mako/database/query/ResultSet.php
src/mako/pagination/Pagination.php
src/mako/pagination/PaginationFactory.php
src/mako/pagination/PaginationFactoryInterface.php
src/mako/pagination/PaginationInterface.php
tests/bootstrap.php
tests/integration/database/query/compilers/BaseCompilerTest.php
tests/integration/resources/BuilderTestCase.php
tests/integration/resources/ORMTestCase.php
tests/unit/database/query/compilers/BaseCompilerTest.php
tests/unit/pagination/PaginationTest.php

Hi,
I have made some rather large changes to how pagination works (but the change for a end user should be minimal).
Now we can do like this:
```$users = User::asceding('id')->paginate()```
Thats it! To access the pagination object in your views just do this:
```{{raw:$users->getPagination()->render('pagination')}}```
This works with both the query builder and the ORM.
You can still create pagination objects the old way using ```$this->pagination->create($count);``` as well.
I'll make another pull request to the docs if this gets merged :)

Simplified query builder pagination

---

src/mako/common/ExtendableTrait.php
src/mako/utility/Collection.php
src/mako/utility/HTML.php
tests/unit/common/ExtendableTraitTest.php
tests/unit/utility/CollectionTest.php
tests/unit/utility/HTMLTest.php

This makes it easy to extend Collections with custom methods. We needed a `toJsonWithPagination` method and this seemed like a clean and easy way to do it.
I also made some changes to the HTML helper so that it uses the same `ExtendableTrait`. It causes a minor bc-break (as you can see in the HTML helper unit test) but I think it's worth it when we're jumping to a new major release.

It is now possible to extend Collections with custom methods.

---

src/mako/database/ConnectionManager.php
src/mako/database/query/Query.php
src/mako/database/query/compilers/Compiler.php
src/mako/database/query/compilers/DB2.php
src/mako/database/query/compilers/Firebird.php
src/mako/database/query/compilers/NuoDB.php
src/mako/database/query/compilers/Oracle.php
src/mako/database/query/compilers/Postgres.php
src/mako/database/query/compilers/SQLServer.php
tests/unit/database/query/compilers/BaseCompilerTest.php
tests/unit/database/query/compilers/DB2CompilerTest.php
tests/unit/database/query/compilers/FirebirdCompilerTest.php
tests/unit/database/query/compilers/MySQLCompilerTest.php
tests/unit/database/query/compilers/NuoDBCompilerTest.php
tests/unit/database/query/compilers/OracleCompilerTest.php
tests/unit/database/query/compilers/PostgresCompilerTest.php

I have added support for row-level locking to the query builder. 
All databases supported by the Mako query builder (except for SQLite) support locking and it'll gracefully degrade for the databases that don't support it.
Unit tests included :sake: 
I'm working on a pull request for the docs as well.

Added support for row-level locking to the query builder

---

src/mako/database/ConnectionManager.php
src/mako/database/query/Query.php
src/mako/database/query/compilers/Compiler.php
src/mako/database/query/compilers/MySQL.php
src/mako/database/query/compilers/Oracle.php
src/mako/database/query/compilers/Postgres.php
src/mako/database/query/compilers/SQLServer.php
src/mako/database/query/compilers/SQLite.php
tests/unit/database/query/compilers/BaseCompilerTest.php
tests/unit/database/query/compilers/MySQLCompilerTest.php
tests/unit/database/query/compilers/OracleCompilerTest.php
tests/unit/database/query/compilers/PostgresCompilerTest.php
tests/unit/database/query/compilers/SQLServerCompilerTest.php
tests/unit/database/query/compilers/SQLiteCompilerTest.php

I have added a unified JSON field syntax to the query builder. It supports both JSON arrays and objects (and a mix of both). 
The syntax currently works with Postgres, MySQL and Oracle and it'll throw an exception when used with any other RDBMS. I know SQLite and SQL Server have some limited JSON capabilities but I didn't find enough info.
`$query->table('foobar')->select(['json_column->foo->bar->0->baz'])->all();`

Added unified JSON field syntax

---

composer.json

The version mask currently specified in composer.json does not allow any newer versions, which may cause conflicts with other projects that do require a newer version (such as, for example, GrumPHP).

Allow newer, but backwards-compatible versions of monolog.

---

src/mako/error/handlers/WebHandler.php
src/mako/error/handlers/views/detailed.tpl.php

When the detailed error view is shown by the error handler, it shows the arguments for each entry in the stack trace in a `<pre>` block. It uses `var_dump` to generate a readable version of the variable.
However, if the extension `xdebug` is present, it replaces the builtin `var_dump` with a more readable (and recursion-safe) one. That override already outputs sensible (and safe) HTML. The HTML escape from Mako comes after that, and causes a double escape as shown in the (slightly censored) screenshot below.
This patch checks whether `xdebug` is loaded and if so disables the output escaping. I use this in my own testing environment.
Mako version: 4.x and 5.x
PHP version: Any supported version will do

Add support for xdebug in error handler

---

src/mako/application/cli/commands/migrations/RollbackTrait.php

When trying to rollback migrations everything works fine except in the last step when the command tries to output reverted migrations list.
The 'outputMigrationList' method expects an array parameter but an object is parsed instead.

Fix migration rollback action

---

src/mako/utility/Collection.php
tests/unit/utility/CollectionTest.php

This PR makes closure that get passes into Collection::map() method can accept key as a second argument.
This PR also adds new Collection::reject() method, which is basically a reverse of Collection::filter() method, but can also works with a single value.

Collection::map() improvement

---

src/mako/application/Application.php

I have been toying with php-mp lately and the `MAKO_START` start constant is creating some minor issues. I suggest removing it in Mako 5.4 and replacing it it with `Application::getStartTime()` instead.

Added Application startTime property and getter method

---

src/mako/cache/CacheManager.php
src/mako/cache/stores/APCU.php

---
| Bugfix?      | Yes, see #244       |
| Has unit and/or integration tests?  | No |
---
This patch introduces a configuration option `atomicGetSet` for the APCU cache store, which defaults to true. If false, the store will fall back on `Store::getOrElse` rather than using `apcu_entry`. The default behaviour is the current behaviour.

Implement an opt-out for atomic get/set in APCU.

---

src/mako/error/handlers/web/DevelopmentHandler.php

---
| Bugfix?      | No      |
| Other?       | No      |
| Has unit and/or integration tests?  | No      |
We run Mako for a small team of trusted users. When they encounter an error, they are often helpful enough to share a screenshot of the stack trace. By default, this screenshot contains a list of cookies, including the session cookie. Hence, sharing the screenshot entails a security breach, as our developers do not (and should not) have access to the production database. This PR uses the blacklist feature of Whoops to hide that cookie.

Option to hide session cookie from stack trace.

---

src/mako/database/midgard/ORM.php

---
| Bugfix?      | Yes      |
| New feature? | No      |
| Other?       | No      |
| Has unit and/or integration tests?  | No      |
---
The property `exists` had been removed from the ORM, except in one location. This caused a bug where a record that was removed would suddenly have a new column named `exists` with value `FALSE`. The present PR removes the last occurrence.
...

Truly remove the 'exists' property from ORM.

---

src/mako/http/Request.php
tests/unit/http/RequestTest.php

---
| New feature? | -      |
| Other?       | yes      |
| Has backwards compatibility breaks? | -      |
| Has unit and/or integration tests?  | yes      |
---
If the site is being run behind a proxy or loadbalancer that handles the TLS connection instead of the webserver, `isSecure` will no return as `true`
...

isSecure checks the X-Forwarded-Proto and X-Forwarded-Port headers

---

CHANGELOG.md
src/mako/database/midgard/Query.php
src/mako/database/midgard/relations/BelongsTo.php
src/mako/database/midgard/relations/ManyToMany.php
src/mako/database/midgard/relations/Relation.php
src/mako/database/query/Query.php
tests/integration/database/midgard/relations/AutoEagerLoadingTest.php
tests/integration/database/midgard/relations/BelongsToPolymorphicTest.php
tests/integration/database/midgard/relations/BelongsToTest.php
tests/integration/database/midgard/relations/HasManyPolymorphicTest.php
tests/integration/database/midgard/relations/HasManyTest.php
tests/integration/database/midgard/relations/HasOnePolymorphicTest.php
tests/integration/database/midgard/relations/HasOneTest.php
tests/integration/database/midgard/relations/ManyToManyTest.php
tests/integration/database/midgard/relations/NestedEagerLoadingTest.php
tests/integration/database/midgard/relations/WithCountOfTest.php

---
---
Added a `withCountOf` method to the ORM query builder that allows you to easily add subqueries to count related records.

With count of

---

src/mako/application/cli/commands/server/Server.php
src/mako/cli/input/helpers/Secret.php

fixes #281
---
| Bugfix?      | Yes      |
| New feature? | No      |
| Other?       | No      |
| Has unit and/or integration tests?  | No      |
---
Fixes issue #281, uses php's `escapeshellcmd()` and `escapeshellarg()` on commands/args that I think needed them.

Escape shell arguments for server and hiddeninput.exe

---

.github/workflows/static-analysis.yml
CHANGELOG.md
src/mako/http/routing/Dispatcher.php
src/mako/http/routing/Route.php
src/mako/http/routing/attributes/Middleware.php
tests/unit/http/routing/RouteTest.php
tests/unit/http/routing/attributes/MiddlewareTest.php

---
---
This feature makes it possible to register route middleware using attributes on controller classes and methods when using PHP 8.0+.

Register route middleware using attributes

---

CHANGELOG.md
src/mako/http/routing/Route.php
src/mako/http/routing/attributes/Constraint.php
tests/unit/http/routing/RouteTest.php
tests/unit/http/routing/attributes/ConstraintTest.php

---
---
This feature makes it possible to register route constraints using attributes on controller classes and methods when using PHP 8.0+.

Register route constraints using attributes

---

src/mako/application/services/BusService.php
src/mako/application/services/CommandBusService.php
src/mako/application/services/EventService.php
src/mako/bus/HandlerInterface.php
src/mako/bus/command/CommandBus.php
src/mako/bus/command/CommandBusInterface.php
src/mako/bus/command/exceptions/CommandBusException.php
src/mako/bus/event/EventBus.php
src/mako/bus/event/EventBusInterface.php
src/mako/bus/exceptions/BusException.php
src/mako/bus/query/QueryBus.php
src/mako/bus/query/QueryBusInterface.php
src/mako/bus/query/exceptions/QueryBusException.php
src/mako/bus/traits/ResolveHandlerTrait.php
src/mako/bus/traits/SingleHandlerTrait.php
src/mako/commander/CommandBus.php
src/mako/commander/CommandBusInterface.php
src/mako/commander/CommandHandlerInterface.php
src/mako/commander/CommandInterface.php
src/mako/commander/SelfHandlingCommandInterface.php
src/mako/event/Event.php
src/mako/event/EventHandlerInterface.php
src/mako/syringe/Container.php
src/mako/syringe/traits/ContainerAwareTrait.php
tests/unit/bus/command/CommandBusTest.php
tests/unit/bus/event/EventBusTest.php
tests/unit/bus/query/QueryBusTest.php

---
---
A new and more flexible bus library that replaces the existing command bus and event libraries. The old libraries are deprecated and will be removed in Mako 10.

New bus library

---

CHANGELOG.md
src/mako/http/routing/Dispatcher.php
src/mako/http/routing/Route.php
src/mako/http/routing/Router.php
src/mako/http/routing/Routes.php
src/mako/http/routing/attributes/Constraint.php
src/mako/http/routing/attributes/Middleware.php
tests/unit/FunctionsTest.php
tests/unit/http/routing/DispatcherTest.php
tests/unit/http/routing/RouteTest.php
tests/unit/http/routing/RouterTest.php
tests/unit/http/routing/attributes/ConstraintTest.php
tests/unit/http/routing/attributes/MiddlewareTest.php

---
| Bugfix?      |  No      |
| New feature? |  Yes      |
| Other?       |  Yes      |
| Has backwards compatibility breaks? |  Yes      |
---
Improved registration of middleware and constraints. Middleware and constraints are only registered using the class name and parameters are registered using named parameters or associative arrays.
```php
$routes->get('/articles/{id}', [Articles::class, 'view'])
->patterns(['id' => '[0-9]+'])
->middleware(Cache::class, minutes: 60);
//
#[Middleware(Cache::class, minutes: 60)]
#[Middleware(InputValidation::class)]
class Search
{
public function …
```

Improved middleware and constraint registration

---

src/mako/cli/input/helpers/Secret.php

---
| Bugfix?      | Y      |
| New feature? | N      |
| Other?       | N      |
| Has backwards compatibility breaks? | N      |
| Has unit and/or integration tests?  | N      |
---
I'm running PHP 8.3.10. `mako\cli\input\helpers\Secret::$hasStty` has no starting value, and so when `mako\cli\input\helpers\Secret::hasStty()` tries to check it, we get an error:
```
Error: Typed static property mako\cli\input\helpers\Secret::$hasStty must not be accessed before initialization
Error location: .../vendor/mako/framework/src/mako/cli/input/helpers/Secret.php on line 32
#0 .../vendor/mako/framework/src/mako/cli/input/helpers/Secret.php(46): …
```

Fix stty check

---

src/mako/http/Response.php

---
| Bugfix?      | Y      |
| New feature? | N      |
| Other?       | N      |
| Has backwards compatibility breaks? | N      |
| Has unit and/or integration tests?  | N      |
---
```
str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
```

Use empty string instead of null

---

CHANGELOG.md
src/mako/database/midgard/Query.php
src/mako/database/query/Query.php
src/mako/database/query/compilers/Compiler.php
src/mako/database/query/compilers/Firebird.php
src/mako/database/query/compilers/Postgres.php
src/mako/database/query/compilers/SQLServer.php
src/mako/database/query/compilers/SQLite.php
tests/integration/database/midgard/ORMTest.php
tests/integration/database/query/compilers/BaseCompilerTest.php
tests/unit/database/query/compilers/FirebirdCompilerTest.php
tests/unit/database/query/compilers/PostgresCompilerTest.php
tests/unit/database/query/compilers/SQLServerCompilerTest.php
tests/unit/database/query/compilers/SQLiteCompilerTest.php

---
| Bugfix?      | No      |
| Other?       | No      |
| Has backwards compatibility breaks? | No     |
---
You can now update columns and return the updated values in an atomic operation:
```php
$updated = $query->where('id', '=', 1)
->updateAndReturn(
values: ['jobs_done' => new Raw('jobs_done + 1')],
return: ['jobs_done']
);
var_dump($updated->first()->jobs_done);
```

Added "update and return" to the query builder
